######################################################################
# Automatically generated by qmake (1.07a) Tue Sep 2 16:35:07 2014
######################################################################

TEMPLATE = app
CONFIG -= moc qt
INCLUDEPATH += .
LIBS += -L/usr/lib -lsqlite3 
#DEPENDPATH += /usr/lib

# Input
SOURCES += sqlite_search.cpp
