######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 29 17:20:58 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += watchdog.cpp
