######################################################################
# Automatically generated by qmake (1.07a) Tue Jun 2 11:48:09 2015
######################################################################

TEMPLATE = app
CONFIG -= moc
FLTKDIR = /root/fltk-1.1.0b13_ut_kdevelop

INCLUDEPATH += .
INCLUDEPATH += $$FLTKDIR
LIBS +=  -L/root/fltk-1.1.0b13_ut_kdevelop/lib -lfltk -lX11


# Input
SOURCES += browser.cxx
