######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 20 15:57:58 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += ecg_data.cpp
